apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wep
  name: wep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wep
  strategy: {}
  template:
    metadata:
      labels:
        app: wep
    spec:
      containers:
      - image: prinder009800/wep:latest
        name: wep
        ports:
        - containerPort: 8000
        resources: {}
status: {}
