---  
- name: run nginx comtainer by ansible 
  hosts: prod
  tasks:
    - name: pull image nginx
      community.docker.docker_image:
        name: nginx
        tag: latest
        source: pull

    - name: run container
      community.docker.docker_container: 
        name: lab
        image: nginx:latest
        state: started
        ports: 
          - '80:80' 
...
